import type { TipoCuenta, NaturalezaCuenta } from "@prisma/client";

interface CuentaEstandar {
  codigo: string;
  nombre: string;
  tipo: TipoCuenta;
  naturaleza: NaturalezaCuenta;
  nivel: number;
  permiteMovimiento: boolean;
}

/**
 * Catálogo de cuentas estándar PYMES El Salvador
 * Basado en NIIF para PYMES — estructura jerárquica de 4 niveles
 */
export const CATALOGO_ESTANDAR_SV: CuentaEstandar[] = [
  // ===================== ACTIVOS =====================
  { codigo: "1", nombre: "ACTIVO", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 1, permiteMovimiento: false },
  { codigo: "11", nombre: "ACTIVO CORRIENTE", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 2, permiteMovimiento: false },
  { codigo: "1101", nombre: "Efectivo y Equivalentes", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 3, permiteMovimiento: false },
  { codigo: "110101", nombre: "Caja General", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "110102", nombre: "Caja Chica", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "110103", nombre: "Bancos Cuenta Corriente", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "110104", nombre: "Bancos Cuenta de Ahorro", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "1102", nombre: "Cuentas por Cobrar Comerciales", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 3, permiteMovimiento: false },
  { codigo: "110201", nombre: "Clientes Nacionales", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "110202", nombre: "Documentos por Cobrar", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "110203", nombre: "Provisión Cuentas Incobrables", tipo: "ACTIVO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "1103", nombre: "Inventarios", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 3, permiteMovimiento: false },
  { codigo: "110301", nombre: "Inventario de Mercadería", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "110302", nombre: "Inventario de Materia Prima", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "110303", nombre: "Inventario de Productos Terminados", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "1104", nombre: "Impuestos por Recuperar", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 3, permiteMovimiento: false },
  { codigo: "110401", nombre: "IVA Crédito Fiscal", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "110402", nombre: "Pago a Cuenta Adelantado", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "1105", nombre: "Gastos Pagados por Anticipado", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 3, permiteMovimiento: false },
  { codigo: "110501", nombre: "Seguros Pagados por Anticipado", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "110502", nombre: "Arrendamientos Pagados por Anticipado", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "12", nombre: "ACTIVO NO CORRIENTE", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 2, permiteMovimiento: false },
  { codigo: "1201", nombre: "Propiedad, Planta y Equipo", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 3, permiteMovimiento: false },
  { codigo: "120101", nombre: "Terrenos", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "120102", nombre: "Edificios e Instalaciones", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "120103", nombre: "Maquinaria y Equipo", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "120104", nombre: "Mobiliario y Equipo de Oficina", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "120105", nombre: "Vehículos", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "120106", nombre: "Equipo de Cómputo", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "1202", nombre: "Depreciación Acumulada", tipo: "ACTIVO", naturaleza: "ACREEDORA", nivel: 3, permiteMovimiento: false },
  { codigo: "120201", nombre: "Dep. Acum. Edificios e Instalaciones", tipo: "ACTIVO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "120202", nombre: "Dep. Acum. Maquinaria y Equipo", tipo: "ACTIVO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "120203", nombre: "Dep. Acum. Mobiliario y Equipo", tipo: "ACTIVO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "120204", nombre: "Dep. Acum. Vehículos", tipo: "ACTIVO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "120205", nombre: "Dep. Acum. Equipo de Cómputo", tipo: "ACTIVO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "1203", nombre: "Activos Intangibles", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 3, permiteMovimiento: false },
  { codigo: "120301", nombre: "Programas Informáticos (Software)", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "120302", nombre: "Marcas y Patentes", tipo: "ACTIVO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },

  // ===================== PASIVOS =====================
  { codigo: "2", nombre: "PASIVO", tipo: "PASIVO", naturaleza: "ACREEDORA", nivel: 1, permiteMovimiento: false },
  { codigo: "21", nombre: "PASIVO CORRIENTE", tipo: "PASIVO", naturaleza: "ACREEDORA", nivel: 2, permiteMovimiento: false },
  { codigo: "2101", nombre: "Cuentas por Pagar Comerciales", tipo: "PASIVO", naturaleza: "ACREEDORA", nivel: 3, permiteMovimiento: false },
  { codigo: "210101", nombre: "Proveedores Nacionales", tipo: "PASIVO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "210102", nombre: "Documentos por Pagar", tipo: "PASIVO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "2102", nombre: "Obligaciones con Empleados", tipo: "PASIVO", naturaleza: "ACREEDORA", nivel: 3, permiteMovimiento: false },
  { codigo: "210201", nombre: "Sueldos por Pagar", tipo: "PASIVO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "210202", nombre: "Vacaciones por Pagar", tipo: "PASIVO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "210203", nombre: "Aguinaldo por Pagar", tipo: "PASIVO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "2103", nombre: "Retenciones y Cotizaciones", tipo: "PASIVO", naturaleza: "ACREEDORA", nivel: 3, permiteMovimiento: false },
  { codigo: "210301", nombre: "ISSS por Pagar (cuota empleado)", tipo: "PASIVO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "210302", nombre: "AFP por Pagar (cuota empleado)", tipo: "PASIVO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "210303", nombre: "ISR Retenido por Pagar", tipo: "PASIVO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "210304", nombre: "ISSS por Pagar (cuota patronal)", tipo: "PASIVO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "210305", nombre: "AFP por Pagar (cuota patronal)", tipo: "PASIVO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "210306", nombre: "INSAFORP por Pagar", tipo: "PASIVO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "2104", nombre: "Impuestos por Pagar", tipo: "PASIVO", naturaleza: "ACREEDORA", nivel: 3, permiteMovimiento: false },
  { codigo: "210401", nombre: "IVA Débito Fiscal", tipo: "PASIVO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "210402", nombre: "Pago a Cuenta IVA por Pagar", tipo: "PASIVO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "210403", nombre: "Impuesto sobre la Renta por Pagar", tipo: "PASIVO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "2105", nombre: "Ingresos Recibidos por Anticipado", tipo: "PASIVO", naturaleza: "ACREEDORA", nivel: 3, permiteMovimiento: false },
  { codigo: "210501", nombre: "Anticipos de Clientes", tipo: "PASIVO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "22", nombre: "PASIVO NO CORRIENTE", tipo: "PASIVO", naturaleza: "ACREEDORA", nivel: 2, permiteMovimiento: false },
  { codigo: "2201", nombre: "Préstamos Bancarios Largo Plazo", tipo: "PASIVO", naturaleza: "ACREEDORA", nivel: 3, permiteMovimiento: false },
  { codigo: "220101", nombre: "Préstamos Bancarios L/P", tipo: "PASIVO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "2202", nombre: "Provisiones Largo Plazo", tipo: "PASIVO", naturaleza: "ACREEDORA", nivel: 3, permiteMovimiento: false },
  { codigo: "220201", nombre: "Provisión Indemnizaciones", tipo: "PASIVO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },

  // ===================== CAPITAL / PATRIMONIO =====================
  { codigo: "3", nombre: "PATRIMONIO", tipo: "CAPITAL", naturaleza: "ACREEDORA", nivel: 1, permiteMovimiento: false },
  { codigo: "31", nombre: "CAPITAL SOCIAL", tipo: "CAPITAL", naturaleza: "ACREEDORA", nivel: 2, permiteMovimiento: false },
  { codigo: "3101", nombre: "Capital Social Suscrito y Pagado", tipo: "CAPITAL", naturaleza: "ACREEDORA", nivel: 3, permiteMovimiento: false },
  { codigo: "310101", nombre: "Capital Social", tipo: "CAPITAL", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "32", nombre: "RESERVAS", tipo: "CAPITAL", naturaleza: "ACREEDORA", nivel: 2, permiteMovimiento: false },
  { codigo: "3201", nombre: "Reserva Legal", tipo: "CAPITAL", naturaleza: "ACREEDORA", nivel: 3, permiteMovimiento: false },
  { codigo: "320101", nombre: "Reserva Legal", tipo: "CAPITAL", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "33", nombre: "RESULTADOS", tipo: "CAPITAL", naturaleza: "ACREEDORA", nivel: 2, permiteMovimiento: false },
  { codigo: "3301", nombre: "Resultados de Ejercicios Anteriores", tipo: "CAPITAL", naturaleza: "ACREEDORA", nivel: 3, permiteMovimiento: false },
  { codigo: "330101", nombre: "Utilidades Retenidas", tipo: "CAPITAL", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "330102", nombre: "Pérdidas Acumuladas", tipo: "CAPITAL", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "3302", nombre: "Resultado del Ejercicio", tipo: "CAPITAL", naturaleza: "ACREEDORA", nivel: 3, permiteMovimiento: false },
  { codigo: "330201", nombre: "Utilidad del Ejercicio", tipo: "CAPITAL", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "330202", nombre: "Pérdida del Ejercicio", tipo: "CAPITAL", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },

  // ===================== INGRESOS =====================
  { codigo: "4", nombre: "INGRESOS", tipo: "INGRESO", naturaleza: "ACREEDORA", nivel: 1, permiteMovimiento: false },
  { codigo: "41", nombre: "INGRESOS DE OPERACIÓN", tipo: "INGRESO", naturaleza: "ACREEDORA", nivel: 2, permiteMovimiento: false },
  { codigo: "4101", nombre: "Ventas", tipo: "INGRESO", naturaleza: "ACREEDORA", nivel: 3, permiteMovimiento: false },
  { codigo: "410101", nombre: "Ventas Gravadas", tipo: "INGRESO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "410102", nombre: "Ventas Exentas", tipo: "INGRESO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "410103", nombre: "Devoluciones y Descuentos sobre Ventas", tipo: "INGRESO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "4102", nombre: "Ingresos por Servicios", tipo: "INGRESO", naturaleza: "ACREEDORA", nivel: 3, permiteMovimiento: false },
  { codigo: "410201", nombre: "Servicios Prestados Gravados", tipo: "INGRESO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "410202", nombre: "Servicios Prestados Exentos", tipo: "INGRESO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "42", nombre: "OTROS INGRESOS", tipo: "INGRESO", naturaleza: "ACREEDORA", nivel: 2, permiteMovimiento: false },
  { codigo: "4201", nombre: "Ingresos No Operacionales", tipo: "INGRESO", naturaleza: "ACREEDORA", nivel: 3, permiteMovimiento: false },
  { codigo: "420101", nombre: "Intereses Ganados", tipo: "INGRESO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "420102", nombre: "Utilidad en Venta de Activos", tipo: "INGRESO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "420103", nombre: "Otros Ingresos Diversos", tipo: "INGRESO", naturaleza: "ACREEDORA", nivel: 4, permiteMovimiento: true },

  // ===================== COSTOS =====================
  { codigo: "5", nombre: "COSTOS", tipo: "COSTO", naturaleza: "DEUDORA", nivel: 1, permiteMovimiento: false },
  { codigo: "51", nombre: "COSTO DE VENTAS", tipo: "COSTO", naturaleza: "DEUDORA", nivel: 2, permiteMovimiento: false },
  { codigo: "5101", nombre: "Costo de Mercadería Vendida", tipo: "COSTO", naturaleza: "DEUDORA", nivel: 3, permiteMovimiento: false },
  { codigo: "510101", nombre: "Costo de Ventas de Mercadería", tipo: "COSTO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "510102", nombre: "Costo de Ventas de Servicios", tipo: "COSTO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },

  // ===================== GASTOS =====================
  { codigo: "6", nombre: "GASTOS", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 1, permiteMovimiento: false },
  { codigo: "61", nombre: "GASTOS DE ADMINISTRACIÓN", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 2, permiteMovimiento: false },
  { codigo: "6101", nombre: "Gastos de Personal Administrativo", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 3, permiteMovimiento: false },
  { codigo: "610101", nombre: "Sueldos y Salarios Administrativos", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "610102", nombre: "Horas Extras Administrativas", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "610103", nombre: "ISSS Patronal Administrativo", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "610104", nombre: "AFP Patronal Administrativo", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "610105", nombre: "INSAFORP Administrativo", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "610106", nombre: "Vacaciones Administrativas", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "610107", nombre: "Aguinaldo Administrativo", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "610108", nombre: "Indemnizaciones Administrativas", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "6102", nombre: "Gastos Generales Administrativos", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 3, permiteMovimiento: false },
  { codigo: "610201", nombre: "Arrendamiento de Oficinas", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "610202", nombre: "Servicios Públicos (Agua, Luz, Teléfono)", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "610203", nombre: "Papelería y Útiles", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "610204", nombre: "Mantenimiento y Reparaciones", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "610205", nombre: "Depreciaciones Administrativas", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "610206", nombre: "Seguros", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "62", nombre: "GASTOS DE VENTA", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 2, permiteMovimiento: false },
  { codigo: "6201", nombre: "Gastos de Personal de Ventas", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 3, permiteMovimiento: false },
  { codigo: "620101", nombre: "Sueldos Vendedores", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "620102", nombre: "Comisiones sobre Ventas", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "620103", nombre: "ISSS Patronal Ventas", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "620104", nombre: "AFP Patronal Ventas", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "6202", nombre: "Gastos Generales de Venta", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 3, permiteMovimiento: false },
  { codigo: "620201", nombre: "Publicidad y Propaganda", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "620202", nombre: "Transporte y Distribución", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "620203", nombre: "Empaque y Embalaje", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "63", nombre: "GASTOS FINANCIEROS", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 2, permiteMovimiento: false },
  { codigo: "6301", nombre: "Gastos Financieros", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 3, permiteMovimiento: false },
  { codigo: "630101", nombre: "Intereses sobre Préstamos", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "630102", nombre: "Comisiones Bancarias", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
  { codigo: "630103", nombre: "Diferencial Cambiario", tipo: "GASTO", naturaleza: "DEUDORA", nivel: 4, permiteMovimiento: true },
];
